[config]
default_prefix = "@"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'
