[config]
default_prefix = "@"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kitty +kitten themes --reload-in=all matugen"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs || true'

[templates.ncspot]
input_path = '~/.config/matugen/ncspot.toml'
output_path = '~/.config/ncspot/config.toml'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/cava-colors.ini'
post_hook = 'pkill -USR1 cava || true'

[templates.firefox]
input_path = '~/.config/matugen/templates/textfox.css'
output_path = '/home/lucas/.config/mozilla/firefox/01tcjyrm.default-release/chrome/matugen-colors.css'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.hyprlock]
input_path  = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock-colors.conf'
