# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#e675fb", bg = "#e675fb" }
marker_cut      = { fg = "#f8d8fe", bg = "#f8d8fe" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dbbde2", bg = "#dbbde2" }

# Count
count_copied   = { fg = "#27132f", bg = "#f8d8fe" }
count_cut      = { fg = "#27132f", bg = "#f8d8fe" }
count_selected = { fg = "#03305f", bg = "#dbbde2" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#a7c8ff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "‚ñà", close = "‚ñà" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#a7c8ff", bold = true, bg = "#111318" }
inactive  = { fg = "#bdc7dc", bg = "#111318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#a7c8ff", fg = "#03305f", bold = true }
normal_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Select mode
select_main = { bg = "#bdc7dc", fg = "#273141", bold = true }
select_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Unset mode
unset_main = { bg = "#dbbde2", fg = "#3e2845", bold = true }
unset_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "ü≠Å", close = "ü≠†" }
sep_right = { open = "ü≠Å", close = "ü≠†" }

# Permissions
perm_type  = { fg = "#5972a7" }
perm_write = { fg = "#a153b3" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#dd43fa" }
perm_sep   = { fg = "#3c7dff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#a7c8ff", bg = "#37393e" }
progress_error  = { fg = "#ffb4ab", bg = "#37393e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393e" }
cand = { fg = "#a7c8ff" }
rest = { fg = "#03305f" }
desc = { fg = "#e1e2e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e2e9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#dbbde2" }
title_warn  = { fg = "#a7c8ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#a7c8ff" }
active = { fg = "#dbbde2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#a7c8ff" }
value  = { fg = "#e1e2e9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#a7c8ff", bg = "#03305f" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#a7c8ff" }
title   = {}
hovered = { fg = "#f8d8fe", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e1e2e9" }
run    = { fg = "#e1e2e9" }
footer = { fg = "#273141", bg = "#bdc7dc" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e1e2e9" },
    { url = "*/", fg = "#a7c8ff" },
]

# : ]]]
