use_nerdfont = true
flip_status_indicators = true

[ncspot]
draw_covers = true
cover_backend = "kitty"

[theme]
# Couleurs de base (Inspiré de ton setup Gruvbox)
background = "#0f1416"
primary = "#dee3e6"
secondary = "#bfc8cb"
title = "#85d2e8"

# Musique en cours
playing = "#85d2e8"
playing_selected = "#afecff"
playing_bg = "#004e5d"

# Points saillants et sélection
highlight = "#cee7ef"
highlight_bg = "#344a51"

# Erreurs
error = "#ffb4ab"
error_bg = "#93000a"

# Barre de statut
statusbar = "#bfc8cb"
statusbar_progress = "#85d2e8"
statusbar_bg = "#252b2d"

# Ligne de commande
cmdline = "#dee3e6"
cmdline_bg = "#252b2d"

# Recherche
search_match = "#c0c4eb"
